### ISSUE TITLE
Giving Error when trying with MNIST data

### ISSUE THREAD

**Issue by ArghyaPal** [staturecrane/dcgan_vae_torch#1]
I am very new to torch. I wish to run MNIST dataset. Would you please share with me how to run MNIST dataset on the same code?

**Comment by staturecrane** [comment]
@ArghyaPal Have you changed the "channels" value to 1 and the "dim" value to the resolution of your MNIST images? 

Also, the data loader expects a single folder of images without subdirectories. Make sure you have all the images concatenated into a single folder, or otherwise modify the code to look through subdirectories.

In any follow-up comments, please provide the actual error Torch is throwing, to help me assist you better.
